CREATE TABLE `ft_warn_rec` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '唯一编码',
  `equip_position` varchar(40) DEFAULT NULL COMMENT '装备位置',
  `equip_type` varchar(40) DEFAULT NULL COMMENT '装备型号',
  `equip_sn` varchar(40) DEFAULT NULL COMMENT '装备序列号',
  `sys_code` varchar(40) DEFAULT NULL COMMENT '功能分类编码',
  `mtr_code` varchar(40) DEFAULT NULL COMMENT '部件物料号',
  `supplier_code` varchar(40) DEFAULT NULL COMMENT '供应商编码',
  `area_code` varchar(40) DEFAULT NULL COMMENT '区域编码',
  `part_bei` varchar(40) DEFAULT NULL COMMENT '部件bei',
  `part_sn` varchar(40) DEFAULT NULL COMMENT '部件序列号',
  `warn_code` varchar(20) DEFAULT NULL COMMENT '虚警规则Code',
  `warn_name` varchar(500) DEFAULT NULL COMMENT '虚警规则名称',
  `warn_level` varchar(20) DEFAULT NULL COMMENT '虚警规则等级',
  `warn_time` datetime(3) DEFAULT NULL COMMENT '虚警告警时间',
  `expression1` varchar(4000) DEFAULT NULL COMMENT '虚警规则公式1',
  `param_data1` varchar(4000) DEFAULT NULL COMMENT '虚警规则公式1参数',
  `expression2` varchar(4000) DEFAULT NULL COMMENT '虚假规则公式2',
  `param_data2` varchar(4000) DEFAULT NULL COMMENT '虚警规则公式2参数',
  `warn_type` varchar(2) DEFAULT NULL COMMENT '预警类型 01、阈值；02、趋势；03、告警；\r\n            11：模型阈值；12：趋势阈值',
  `warn_remark` varchar(200) DEFAULT NULL COMMENT '虚警规则备注',
  `occur_status` varchar(1) DEFAULT NULL COMMENT '发生状态',
  `warn_status` varchar(1) DEFAULT NULL COMMENT '虚警状态',
  `occur_count` int(11) DEFAULT NULL COMMENT '发生次数',
  `occur_detail` blob COMMENT '发生恢复记录详情，格式\r\n[{\r\n  warnTime: 1531710422000, //时间戳，毫秒数\r\n  occurStatus : ''1'', //1发生 0恢复\r\n  paramData1:'''',\r\n  paramData2:''''\r\n}]',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `recInfo_Id` varchar(36) DEFAULT NULL COMMENT 'redis故障预警、告警记录ID',
  `reason` varchar(255) DEFAULT NULL,
  `param_data3` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ft_type` (`warn_type`),
  KEY `idx_ft_warn_time` (`warn_time`),
  KEY `idx_ft_sys_code` (`sys_code`),
  KEY `idx_ft_warn_lvl` (`warn_level`),
  KEY `idx_ft_occur_status` (`occur_status`),
  KEY `idx_ft_warn_status` (`warn_status`) U